/*
Copyright 2019 The Tekton Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1"
	scheme "github.com/tektoncd/pipeline/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ArtifactInstancesGetter has a method to return a ArtifactInstanceInterface.
// A group's client should implement this interface.
type ArtifactInstancesGetter interface {
	ArtifactInstances(namespace string) ArtifactInstanceInterface
}

// ArtifactInstanceInterface has methods to work with ArtifactInstance resources.
type ArtifactInstanceInterface interface {
	Create(*v1alpha1.ArtifactInstance) (*v1alpha1.ArtifactInstance, error)
	Update(*v1alpha1.ArtifactInstance) (*v1alpha1.ArtifactInstance, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.ArtifactInstance, error)
	List(opts v1.ListOptions) (*v1alpha1.ArtifactInstanceList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ArtifactInstance, err error)
	ArtifactInstanceExpansion
}

// artifactInstances implements ArtifactInstanceInterface
type artifactInstances struct {
	client rest.Interface
	ns     string
}

// newArtifactInstances returns a ArtifactInstances
func newArtifactInstances(c *TektonV1alpha1Client, namespace string) *artifactInstances {
	return &artifactInstances{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the artifactInstance, and returns the corresponding artifactInstance object, and an error if there is any.
func (c *artifactInstances) Get(name string, options v1.GetOptions) (result *v1alpha1.ArtifactInstance, err error) {
	result = &v1alpha1.ArtifactInstance{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("artifactinstances").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ArtifactInstances that match those selectors.
func (c *artifactInstances) List(opts v1.ListOptions) (result *v1alpha1.ArtifactInstanceList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ArtifactInstanceList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("artifactinstances").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested artifactInstances.
func (c *artifactInstances) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("artifactinstances").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a artifactInstance and creates it.  Returns the server's representation of the artifactInstance, and an error, if there is any.
func (c *artifactInstances) Create(artifactInstance *v1alpha1.ArtifactInstance) (result *v1alpha1.ArtifactInstance, err error) {
	result = &v1alpha1.ArtifactInstance{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("artifactinstances").
		Body(artifactInstance).
		Do().
		Into(result)
	return
}

// Update takes the representation of a artifactInstance and updates it. Returns the server's representation of the artifactInstance, and an error, if there is any.
func (c *artifactInstances) Update(artifactInstance *v1alpha1.ArtifactInstance) (result *v1alpha1.ArtifactInstance, err error) {
	result = &v1alpha1.ArtifactInstance{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("artifactinstances").
		Name(artifactInstance.Name).
		Body(artifactInstance).
		Do().
		Into(result)
	return
}

// Delete takes name of the artifactInstance and deletes it. Returns an error if one occurs.
func (c *artifactInstances) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("artifactinstances").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *artifactInstances) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("artifactinstances").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched artifactInstance.
func (c *artifactInstances) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ArtifactInstance, err error) {
	result = &v1alpha1.ArtifactInstance{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("artifactinstances").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
