/*
Copyright 2019 The Tekton Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeArtifactInstances implements ArtifactInstanceInterface
type FakeArtifactInstances struct {
	Fake *FakeTektonV1alpha1
	ns   string
}

var artifactinstancesResource = schema.GroupVersionResource{Group: "tekton.dev", Version: "v1alpha1", Resource: "artifactinstances"}

var artifactinstancesKind = schema.GroupVersionKind{Group: "tekton.dev", Version: "v1alpha1", Kind: "ArtifactInstance"}

// Get takes name of the artifactInstance, and returns the corresponding artifactInstance object, and an error if there is any.
func (c *FakeArtifactInstances) Get(name string, options v1.GetOptions) (result *v1alpha1.ArtifactInstance, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(artifactinstancesResource, c.ns, name), &v1alpha1.ArtifactInstance{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ArtifactInstance), err
}

// List takes label and field selectors, and returns the list of ArtifactInstances that match those selectors.
func (c *FakeArtifactInstances) List(opts v1.ListOptions) (result *v1alpha1.ArtifactInstanceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(artifactinstancesResource, artifactinstancesKind, c.ns, opts), &v1alpha1.ArtifactInstanceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ArtifactInstanceList{ListMeta: obj.(*v1alpha1.ArtifactInstanceList).ListMeta}
	for _, item := range obj.(*v1alpha1.ArtifactInstanceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested artifactInstances.
func (c *FakeArtifactInstances) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(artifactinstancesResource, c.ns, opts))

}

// Create takes the representation of a artifactInstance and creates it.  Returns the server's representation of the artifactInstance, and an error, if there is any.
func (c *FakeArtifactInstances) Create(artifactInstance *v1alpha1.ArtifactInstance) (result *v1alpha1.ArtifactInstance, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(artifactinstancesResource, c.ns, artifactInstance), &v1alpha1.ArtifactInstance{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ArtifactInstance), err
}

// Update takes the representation of a artifactInstance and updates it. Returns the server's representation of the artifactInstance, and an error, if there is any.
func (c *FakeArtifactInstances) Update(artifactInstance *v1alpha1.ArtifactInstance) (result *v1alpha1.ArtifactInstance, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(artifactinstancesResource, c.ns, artifactInstance), &v1alpha1.ArtifactInstance{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ArtifactInstance), err
}

// Delete takes name of the artifactInstance and deletes it. Returns an error if one occurs.
func (c *FakeArtifactInstances) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(artifactinstancesResource, c.ns, name), &v1alpha1.ArtifactInstance{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeArtifactInstances) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(artifactinstancesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.ArtifactInstanceList{})
	return err
}

// Patch applies the patch and returns the patched artifactInstance.
func (c *FakeArtifactInstances) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ArtifactInstance, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(artifactinstancesResource, c.ns, name, pt, data, subresources...), &v1alpha1.ArtifactInstance{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ArtifactInstance), err
}
