/*
Copyright 2019 The Tekton Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeArtifacts implements ArtifactInterface
type FakeArtifacts struct {
	Fake *FakeTektonV1alpha1
	ns   string
}

var artifactsResource = schema.GroupVersionResource{Group: "tekton.dev", Version: "v1alpha1", Resource: "artifacts"}

var artifactsKind = schema.GroupVersionKind{Group: "tekton.dev", Version: "v1alpha1", Kind: "Artifact"}

// Get takes name of the artifact, and returns the corresponding artifact object, and an error if there is any.
func (c *FakeArtifacts) Get(name string, options v1.GetOptions) (result *v1alpha1.Artifact, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(artifactsResource, c.ns, name), &v1alpha1.Artifact{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Artifact), err
}

// List takes label and field selectors, and returns the list of Artifacts that match those selectors.
func (c *FakeArtifacts) List(opts v1.ListOptions) (result *v1alpha1.ArtifactList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(artifactsResource, artifactsKind, c.ns, opts), &v1alpha1.ArtifactList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ArtifactList{ListMeta: obj.(*v1alpha1.ArtifactList).ListMeta}
	for _, item := range obj.(*v1alpha1.ArtifactList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested artifacts.
func (c *FakeArtifacts) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(artifactsResource, c.ns, opts))

}

// Create takes the representation of a artifact and creates it.  Returns the server's representation of the artifact, and an error, if there is any.
func (c *FakeArtifacts) Create(artifact *v1alpha1.Artifact) (result *v1alpha1.Artifact, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(artifactsResource, c.ns, artifact), &v1alpha1.Artifact{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Artifact), err
}

// Update takes the representation of a artifact and updates it. Returns the server's representation of the artifact, and an error, if there is any.
func (c *FakeArtifacts) Update(artifact *v1alpha1.Artifact) (result *v1alpha1.Artifact, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(artifactsResource, c.ns, artifact), &v1alpha1.Artifact{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Artifact), err
}

// Delete takes name of the artifact and deletes it. Returns an error if one occurs.
func (c *FakeArtifacts) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(artifactsResource, c.ns, name), &v1alpha1.Artifact{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeArtifacts) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(artifactsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.ArtifactList{})
	return err
}

// Patch applies the patch and returns the patched artifact.
func (c *FakeArtifacts) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Artifact, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(artifactsResource, c.ns, name, pt, data, subresources...), &v1alpha1.Artifact{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Artifact), err
}
