/*
Copyright 2019 The Tekton Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeArtifactTypes implements ArtifactTypeInterface
type FakeArtifactTypes struct {
	Fake *FakeTektonV1alpha1
	ns   string
}

var artifacttypesResource = schema.GroupVersionResource{Group: "tekton.dev", Version: "v1alpha1", Resource: "artifacttypes"}

var artifacttypesKind = schema.GroupVersionKind{Group: "tekton.dev", Version: "v1alpha1", Kind: "ArtifactType"}

// Get takes name of the artifactType, and returns the corresponding artifactType object, and an error if there is any.
func (c *FakeArtifactTypes) Get(name string, options v1.GetOptions) (result *v1alpha1.ArtifactType, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(artifacttypesResource, c.ns, name), &v1alpha1.ArtifactType{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ArtifactType), err
}

// List takes label and field selectors, and returns the list of ArtifactTypes that match those selectors.
func (c *FakeArtifactTypes) List(opts v1.ListOptions) (result *v1alpha1.ArtifactTypeList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(artifacttypesResource, artifacttypesKind, c.ns, opts), &v1alpha1.ArtifactTypeList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ArtifactTypeList{ListMeta: obj.(*v1alpha1.ArtifactTypeList).ListMeta}
	for _, item := range obj.(*v1alpha1.ArtifactTypeList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested artifactTypes.
func (c *FakeArtifactTypes) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(artifacttypesResource, c.ns, opts))

}

// Create takes the representation of a artifactType and creates it.  Returns the server's representation of the artifactType, and an error, if there is any.
func (c *FakeArtifactTypes) Create(artifactType *v1alpha1.ArtifactType) (result *v1alpha1.ArtifactType, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(artifacttypesResource, c.ns, artifactType), &v1alpha1.ArtifactType{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ArtifactType), err
}

// Update takes the representation of a artifactType and updates it. Returns the server's representation of the artifactType, and an error, if there is any.
func (c *FakeArtifactTypes) Update(artifactType *v1alpha1.ArtifactType) (result *v1alpha1.ArtifactType, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(artifacttypesResource, c.ns, artifactType), &v1alpha1.ArtifactType{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ArtifactType), err
}

// Delete takes name of the artifactType and deletes it. Returns an error if one occurs.
func (c *FakeArtifactTypes) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(artifacttypesResource, c.ns, name), &v1alpha1.ArtifactType{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeArtifactTypes) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(artifacttypesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.ArtifactTypeList{})
	return err
}

// Patch applies the patch and returns the patched artifactType.
func (c *FakeArtifactTypes) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ArtifactType, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(artifacttypesResource, c.ns, name, pt, data, subresources...), &v1alpha1.ArtifactType{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ArtifactType), err
}
