kind: Task
apiVersion: tekton.dev/v1beta1
metadata:
  name: wf-test
spec:
  workspaces:
  - name: config
    files:
    - name: webpack-config
      path: "/webpack.config.js"
  steps:
  - name: foo
    image: node:alpine
    script: |
      #!/usr/bin/env ash
      echo "File path variable: $(workspaces.config.files.webpack-config.path)"
      node "$(workspaces.config.files.webpack-config.path)"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: cm
data:
  webpack.config.js: |
    console.log('TODO(sbws): write the webpack config');
---
kind: TaskRun
apiVersion: tekton.dev/v1beta1
metadata:
  name: run-wf-test
spec:
  taskRef:
    name: wf-test
  workspaces:
  - name: config
    configMap:
      name: cm
