kind: Task
apiVersion: tekton.dev/v1beta1
metadata:
  name: node-build
spec:
  workspaces:
  - name: source
  steps:
  - name: build
    image: node:alpine
    script: |
      #!/usr/bin/env ash
      cd $(workspaces.source.path)
      node ./build.js
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: example-source-code
data:
  # uh-oh! wrong filename; expects build.js
  compile.js: |
    // build and minify
    console.log('Hello, world!');
---
kind: TaskRun
apiVersion: tekton.dev/v1beta1
metadata:
  name: run-node-build
spec:
  taskRef:
    name: node-build
  workspaces:
  - name: source
    configMap:
      name: example-source-code
