apiVersion: tekton.dev/v1alpha1
kind: ArtifactType
metadata:
  name: simple-git
spec:
  readOnlyMode:
    description: In read-only mode, this simple artifact type clones a given repo url in to a given directory.
    params:
    - name: url
      description: "The repo url to clone."
    - name: ref
      description: "The git ref to checkout."
      default: "master"
    results:
    - name: readSHA
      description: "The HEAD SHA that was received by cloning the repo url."
    preRunSteps:
    - name: simple-git-clone-repo
      image: alpine/git
      script: |
        #!/usr/bin/env sh
        set -e
        set -x
        git clone $(params.url) $(name)
        cd $(name)
        git checkout $(params.ref)
        cat > /dev/termination-log << TEKTONEOF
          [
            {
              "key": "$(name).readSHA",
              "value": "$(git rev-parse HEAD)"
            },
            {
              "key": "$(name).url",
              "value": "$(params.url)"
            },
            {
              "key": "$(name).ref",
              "value": "$(params.ref)"
            }
          ]
        TEKTONEOF
  readWriteMode:
    description: In read-write mode, clone repo and then push any changes.
    params:
    - name: url
      description: "The repo url to clone."
    - name: ref
      description: "The git ref to checkout."
      default: "master"
    - name: commit-message
      description: "The commit message to use when committing and pushing changes back."
    results:
    - name: readSHA
      description: "The HEAD SHA that was received by cloning the repo url."
    - name: writtenSHA
      description: "The HEAD SHA that was pushed to the repo url."
    preRunSteps:
    - name: simple-git-clone-repo
      image: alpine/git
      script: |
        #!/usr/bin/env sh
        set -e
        set -x
        git clone $(params.url) $(name)
        cd $(name)
        git checkout $(params.ref)
        echo "[{ \"key\": \"$(name).readSHA\", \"value\": \"$(git rev-parse HEAD)\" }]" > /dev/termination-log
    postRunSteps:
    - name: simple-git-push-repo
      image: alpine/git
      script: |
        #!/usr/bin/env sh
        set -e
        set -x
        cd $(name)
        git add --all
        git commit -m "$(params.commit-message)"
        git push origin
        echo "[{ \"name\": \"$(name).writtenSHA\", \"value\": \"$(git rev-parse HEAD)\" }]" > /dev/termination-log
  createMode:
    results:
    - name: url
      description: "A repo url generated by the task."
    - name: ref
      description: "A git ref to checkout."
