kind: PipelineRun
apiVersion: tekton.dev/v1beta1
metadata:
  generateName: test-pipelinerun-
spec:
  pipelineSpec:
    tasks:
    - name: task1
      params:
      - name: pipeline-uid
        value: "$(context.pipelineRun.uid)"
      taskSpec:
        params:
        - name: pipeline-uid
        steps:
        - image: ubuntu
          name: print-uid
          script: |
            echo "TaskRun UID: $(context.taskRun.uid)"
            echo "PipelineRun UID: $(params.pipeline-uid)"
