# This example TaskRun demonstrates how to isolate a Workspace to specific Steps
# and Sidecars.
#
# The Step writes a file to the Workspace and then waits for the Sidecar
# to respond. The Sidecar sees the Step's file and writes its response.
# The Step sees the response and exits.
kind: TaskRun
apiVersion: tekton.dev/v1beta1
metadata:
  generateName: workspace-isolation-
spec:
  timeout: 2m0s
  workspaces:
  - name: signals
    emptyDir: {}
  taskSpec:
    workspaces:
    - name: signals
    steps:
    - image: alpine:3.12.0
      workspaces:
      - name: signals
      script: |
        #!/usr/bin/env ash
        echo "hello world" > "$(workspaces.signals.path)"/start
        echo "Signalled start"
        while [ ! -f "$(workspaces.signals.path)"/ready ] ; do
          echo "Waiting for $(workspaces.signals.path)/ready"
          sleep 1
        done
        echo "Saw ready file"
    - image: alpine:3.12.0
      script: |
        #!/usr/bin/env ash
        if [ -f "$(workspaces.signals.path)"/start ] ; then
          echo "This step should not have access to the signals workspace."
          exit 255
        fi
    sidecars:
    - image: alpine:3.12.0
      workspaces:
      - name: signals
      script: |
        #!/usr/bin/env ash
        while [ ! -f "$(workspaces.signals.path)"/start ] ; do
          echo "Waiting for $(workspaces.signals.path)/start"
          sleep 1
        done
        touch "$(workspaces.signals.path)"/ready
        echo "Wrote ready file"
    - image: alpine:3.12.0
      script: |
        #!/usr/bin/env ash
        if [ -f "$(workspaces.signals.path)"/ready ] ; then
          echo "This sidecar should not have access to the signals workspace."
          exit 255
        fi
